### ISSUE TITLE
solution 상세 페이지 구현

### ISSUE THREAD

**Issue by le2sky** [woowacourse-teams/2024-devel-up#211]
#### 설명

solution 상세 페이지 구현

#### 작업 목록

- [x] solution 상세 페이지 구현

**Comment by le2sky** [comment]
@Parkhanyoung  

해당 이슈 기반으로 백엔드 PR 하나 올렸어요.  https://github.com/woowacourse-teams/2024-devel-up/pull/223
이번 스프린트에서 솔루션 상세 페이지 개발 예정 되어 있을까요? 그렇다면 해당 PR에서 close 처리하지 않을게요.
만약 그게 아니라면,  해당 PR에서 close 처리하고 현재 이슈 제목을 바꾸도록 할게요.

**Comment by Parkhanyoung** [comment]
@le2sky 
디자인이 안 나와서 다음 스프린트 때 개발 예정입니다!

> 해당 PR에서 close 처리하고 현재 이슈 제목을 바꾸는 것이 나을까요?
