### ISSUE TITLE
시작하기 버튼을 누른 뒤 미션 제출방법 안내 모달이 표시되지 않는 현상

### ISSUE THREAD

**Issue by robinjoon** [woowacourse-teams/2024-devel-up#252]
#### 문제 설명 

로그인 상태에서 미션 시작하기 버튼을 누를 경우 제출 방법 안내 모달이 표시되지 않고, 바로 미션 제출하기 버튼으로 변경됨.

#### 재현 방법

다음 순서에 따라서 재현 가능 :

1. 로그인
2. 미션 선택
3. 미션 시작하기 버튼 클릭

#### 예상되는 문제점

이 부분을 제거하고 예상되는 문제점을 작성해주세요.

#### 사진

사진 첨부가 필요할 경우 첨부해주세요.

#### 기타

이 부분을 제거하고 기타 메모할 내용을 자유롭게 작성해주세요.

**Comment by Parkhanyoung** [comment]
해결 완료
