### ISSUE TITLE
[4차 스프린트 - 백엔드] 인프라 구조도 그리기

### ISSUE THREAD

**Issue by Minjoo522** [woowacourse-teams/2024-devel-up#264]
#### 논의가 필요한 내용

월요일에 같이 그릴 예정입니다!

- [ ] 프로덕션, 개발 서버 + DB까지 인프라 구조도 관련 의견
- [ ] 어떤 DB 사용할지 의견

코멘트 달아주세요!

**Comment by robinjoon** [comment]
DBMS 종류 관련 의견은 나중에 덧붙일 예정!
# 전체 인프라 구조
## 다이어그램
![데벨업-데벨업 운영 서버 추가 후 아키텍처 - 로빈 drawio (1)](https://github.com/user-attachments/assets/0b0f1c33-ea9e-4790-a1c2-79796f60e8a8)
## 기존 구조와의 변경점 및 이유
1. DB 서버 추가
2. 운영 서버 추가
3. 프롬테일 추가
### DB 서버 추가
#### RDS 와의 비교
비용이 싸고 더 많은 것을 설정할 수 있다는 장점이 있다. 손수 서버에 접속해서 여러 명령어를 사용하여 여러가지를 설정하게 될텐데, 이 과정에서 우리가 채택한 DBMS에 대해 많은 것을 알 수 있다.
반면, RDS를 사용하면 RDS가 제공하는 많은 관리 기능을 사용할 수 있다는 장점이 있다. 

#### 개발 서버의 DB는 퍼블릭하게 열자
이 부분은 기술지원 채널에서 문의를 해야 할 것 같다. 개발 서버라는 특성 상 편리하게 접근해 여러 작업을 할 수 있는 편리성 측면에서 퍼블릭 서브넷에 속하도록 설정하는 것이 좋을 것 같다는 생각이다. 

### 운영 서버 추가
#### 개발 서버와 EC2 레벨에서 분리한 이유
만약 개발 서버와 운영 서버가 같은 EC2를 사용하고 도커 등의 컨테이너 레벨이나 프로세스 레벨로 분리되어 있을 경우 인프라 비용을 낮출 수 있다는 장점이 있다.

반면, 개발 서버의 장애가 운영 서버의 장애로 번질 가능성이 있는 점이 단점이다. 운영 서버가 안정적일 수 있다면 인프라 비용도 생각보다 낮게 계산(우테코가 AWS 할인 플랜 적용을 받고 있다.)되기 때문에 추가적인 인프라 비용을 감내하는 것이 합리적이라 생각한다.

### 프롬테일 추가
#### Nginx 로그 수집
3차 데모데이 구구의 피드백에서 우리가 Nginx의 로그를 모니터링 대상에서 간과하고 있었다는 것을 알았다. 기본적으로 로그 파일이 EC2에 저장되는데, 이를 모니터링 시스템에서 확인할 수 있게 하려면 프롬테일을 이용해 로키로 전송하면 된다.

비록 또 다른 구성 요소가 추가된다는 점에서 관리 요소가 늘어나는 단점이 있지만 로그를 우테코 캠퍼스 외부에서 보려면 지금 시스템을 유지하면서 할 다른 방법이 없다.

**Comment by lilychoibb** [comment]
https://suave-bearskin-3ab.notion.site/DB-527fcc4b50304c5d9fe1b399de897a01?pvs=4

**Comment by Minjoo522** [comment]
- 다이어그램은 캠퍼스 도착해서 올리겠음
[🗄️ 데이터베이스](https://minjoo522.notion.site/535585fdb48c4874bc2e885757b0848d?p vs=4)

**Comment by alstn113** [comment]
https://alstn113.notion.site/08-12-d7928cafc4b345faa46499cec43752c9

**Comment by le2sky** [comment]
프로덕션, 개발 서버 + DB까지 인프라 구조도 관련 의견
- 개발 DB와 프로덕션 DB를 분리하는 것이 좋다고 생각했어요.
    - 근거는 프로덕션에 배포되기 이전에 슬로우 쿼리를 파악하기 위해서는 개발 DB에 더미 데이터를 쌓아두는 것이 유용하다고 생각했기 때문입니다.

어떤 DB 사용할지 의견
- RDBM를 고려한다.
    - 프로젝트 특성상 다루는 데이터가 관계형, 정형 데이터이기 때문에 RDBMS를 선택합니다.
